#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define ID_FILE_EXIT            40000
#define ID_EDIT_COPYCONTENTS    40001
#define ID_HELP_ABOUT           40002

#endif // RESOURCE_H_INCLUDED
